/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.2
*/

import { ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { SparkMarket } from './SparkMarket.js';

const bytecode = decompressBytecode("");

export class SparkMarketFactory extends ContractFactory<SparkMarket> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      SparkMarket.abi,
      accountOrProvider,
      SparkMarket.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new SparkMarketFactory(wallet);
    return factory.deploy(options);
  }
}
