/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */
    
import { FuelAbstractProcessor, FuelContractContext, FuelProcessorConfig, TypedCall, FuelFetchConfig, FuelCall, FuelLog, addFuelProcessor, getFuelProcessor, FuelBaseProcessorTemplate } from '@sentio/sdk/fuel'
import {Option,Enum,Vec} from './common.js'
import {AuthErrorInput,AuthErrorOutput,MarketRegistryErrorInput,MarketRegistryErrorOutput,MarketRegisterEventInput,MarketRegisterEventOutput,MarketUnregisterEventInput,MarketUnregisterEventOutput,AddressInput,AddressOutput,AssetIdInput,AssetIdOutput,ContractIdInput,ContractIdOutput, SparkRegistry} from './SparkRegistry.js'

import type { BigNumberish, BN } from 'fuels';
import type { BytesLike, Bytes } from 'fuels';


namespace SparkRegistryNS {
  export abstract class CallWithLogs<T extends Array<any>, R> extends TypedCall<T, R> {

    getLogsOfTypeAuthError(): Array<AuthErrorOutput> {
      return this.logs?.filter(l =>["487470194140633944"].includes(l.logId) ).map(l => l.data) as Array<AuthErrorOutput>
    }

    getLogsOfTypeMarketRegistryError(): Array<MarketRegistryErrorOutput> {
      return this.logs?.filter(l =>["12854673644547923665"].includes(l.logId) ).map(l => l.data) as Array<MarketRegistryErrorOutput>
    }

    getLogsOfTypeMarketRegisterEvent(): Array<MarketRegisterEventOutput> {
      return this.logs?.filter(l =>["16526329487357911494"].includes(l.logId) ).map(l => l.data) as Array<MarketRegisterEventOutput>
    }

    getLogsOfTypeMarketUnregisterEvent(): Array<MarketUnregisterEventOutput> {
      return this.logs?.filter(l =>["8687802410378175690"].includes(l.logId) ).map(l => l.data) as Array<MarketUnregisterEventOutput>
    }
  }


}

type LogIdFilter<T> = T | T[]
const LogAuthErrorId = "487470194140633944"
const LogMarketRegistryErrorId = "12854673644547923665"
const LogMarketRegisterEventId = "16526329487357911494"
const LogMarketUnregisterEventId = "8687802410378175690"

export class SparkRegistryProcessor extends FuelAbstractProcessor<SparkRegistry> {
  static bind(options: Omit<FuelProcessorConfig, 'abi'>) {
    if (!options.name) {
      options.name = "SparkRegistry"
    }
    let processor = getFuelProcessor(options) as SparkRegistryProcessor
    if (!processor) {
      processor = new SparkRegistryProcessor(SparkRegistry.abi, {
        name: 'SparkRegistry',
        ...options,
      })
      addFuelProcessor(options, processor)
    }
    return processor
  }

   

  
  onLogAuthError(handler: (log: FuelLog<AuthErrorOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<AuthErrorOutput>([LogAuthErrorId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketRegistryError(handler: (log: FuelLog<MarketRegistryErrorOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketRegistryErrorOutput>([LogMarketRegistryErrorId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketRegisterEvent(handler: (log: FuelLog<MarketRegisterEventOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketRegisterEventOutput>([LogMarketRegisterEventId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketUnregisterEvent(handler: (log: FuelLog<MarketUnregisterEventOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketUnregisterEventOutput>([LogMarketUnregisterEventId], (log, ctx) => handler(log, ctx))
  }

}

export class SparkRegistryProcessorTemplate extends FuelBaseProcessorTemplate<SparkRegistry> {
  bindInternal(options: Omit<FuelProcessorConfig, 'abi'>) {
    return SparkRegistryProcessor.bind(options)
  }

  
  onLogAuthError(handler: (log: FuelLog<AuthErrorOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<AuthErrorOutput>([LogAuthErrorId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketRegistryError(handler: (log: FuelLog<MarketRegistryErrorOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketRegistryErrorOutput>([LogMarketRegistryErrorId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketRegisterEvent(handler: (log: FuelLog<MarketRegisterEventOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketRegisterEventOutput>([LogMarketRegisterEventId], (log, ctx) => handler(log, ctx))
  }

  onLogMarketUnregisterEvent(handler: (log: FuelLog<MarketUnregisterEventOutput>, ctx: FuelContractContext<SparkRegistry>) => void | Promise<void>) {
    return super.onLog<MarketUnregisterEventOutput>([LogMarketUnregisterEventId], (log, ctx) => handler(log, ctx))
  }
}

